### PR TITLE
Get Token function

### PR DESCRIPTION
**Pull request by mvrhov**
Token returns the token value that represents given session data.
You can use this token to build user to session map

### CODE REVIEW

**Comment by alexedwards** [comment]
Thanks for the PR : )

There are a couple of things that I wanted to talk through before merging...

- When a new user visits the site (without an existing session), a new empty `Session` object will be created for them, but the `Session.token` value isn't populated until the session is modified in some way (i.e. `Session.write()` is called). This means that the `GetToken` method as per the PR may return the empty string "". Can you see that being a problem?
- That could be addressed by populating `Session.token` when the `Session` object is first created. But if the session _isn't modified_ in that request cycle and the token isn't commited to the store, then the token `GetToken` returns would not be invalid and not recognized on subsequent requests. I think that's probably worse and more confusing that returning the empty string.

It's also worth mentioning that if you're using the `CookieStore` store implementation, then the `Session.token` value will completely change each time the session is modified.

**Comment by mvrhov** [comment]
For me personally it's not a problem. I need to do a user to a session mapping, so the user can see which active sessions it has and terminate them if needed. 

Maybe all that's needed is to change the GoDoc to:
```
// Token returns the token value that represents given session data.
// You can use this token to build user to session map
// NOTE: The function returns empty string if session hasn't yet been written to
// The return value when using CookieStore is probably useless as it changes with each session write
```

**Comment by alexedwards** [comment]
That sounds good to me. Could you update the PR so the comment reads as follows? I'll then get it merged.

> // Token returns the token value that represents given session data.
// NOTE: The method returns the empty string if session hasn't yet been written to the store.
// If you're using the CookieStore this token will change each time the session is modified.

If possible, could you also use the commit message `[feature] Add GetToken method`? No worries if you can't, but it would be ideal for consistency with previous commits.

Thanks

**Comment by mvrhov** [comment]
Should I also rename the method to `GetToken`? Right now it's just `Token`

**Comment by alexedwards** [comment]
Sorry, hadn't spotted that. Calling the method `Token` is fine :+1:

**Comment by mvrhov** [comment]
Done. Or rather was done when I asked the last question :)

**Pull request merged**
