### PR TITLE
docs: Enhance Markdown formatting in README

### PR DESCRIPTION
**Pull request by Daniel-Sogbey**
Improve the formatting of the code block in the README by escaping the $ character. This ensures that when users copy the code, the $ sign is not included.

### CODE REVIEW

**Comment by alexedwards** [comment]
As far as I can see, this breaks the formatting of the code block when viewing the README on GitHub (which I think is where it will most commonly be read). See the screenshot below:

image

**Comment by dropwhile** [comment]
@alexedwards I assume they meant do it like this:
````
```sh
go get github.com/alexedwards/scs/v2
```
````

Basically just leaving off the `$` so it is easier for folks to just copy and paste.

**Comment by Daniel-Sogbey** [comment]
Hello @alexedwards new push made

**Comment by Daniel-Sogbey** [comment]
Thanks for the opportunity to contribute ❤️

**Pull request merged**
