### PR TITLE
Fix typo and new stores support

### PR DESCRIPTION
**Pull request by gandaldf**

### CODE REVIEW

**Comment by alexedwards** [comment]
@gandaldf Thanks for this PR :+1: It's on my radar and I'll review and merge as soon as I have a chance!

**Comment by gandaldf** [comment]
No problem @alexedwards I'm working on a last store based on [bun](https://github.com/uptrace/bun) a faster and lighter alternative to GORM.

**Comment by gandaldf** [comment]
@alexedwards here we go, I think that for now there's a good stores selection!

**Comment by alexedwards** [comment]
@gandaldf Thank you, this is really fantastic work and some great additions to the package :+1: 

There was nothing I could immediately see that needed changing, so I'm merging it now...

**Comment by alexedwards** [comment]
@gandaldf I had someone email me to ask if they could pay someone to add support for https://github.com/rqlite/rqlite.

I don't have time to do this, but I thought of you and wondered if you have any interest in doing this as paid work for them? I don't know how much they are offering, and I can't vouch for them as a client, but if you have any interest I'd be happy to put you in touch with them.

**Comment by gandaldf** [comment]
Ok! DM on Twitter, you should find me among your followers.

**Pull request merged**
