### PR TITLE
Bump pgx from v4 to v5

### PR DESCRIPTION
**Pull request by zaeph**
pgxpool@v5 uses New() instead of Connect() to create the pool.

The tests still pass, and everything seems to be working in a project using it (snippetbox in _Let’s Go_).

This is my first PR to a Go project, so please let me know if I’ve done anything wrong.  go.sum seems to have been changed a lot.

### CODE REVIEW

**Comment by chriswhiteoco** [comment]
I was just about to do this same thing.  Please accept this pull request.

**Comment by alexedwards** [comment]
@zaeph Thanks : ) 

Could you possibly reflect these changes in the README file to complete the PR?

**Comment by zaeph** [comment]
> Could you possibly reflect these changes in the README file to complete the PR?

Sure, I’ll have a look now.

**Comment by zaeph** [comment]
I think a82c3af678916973705c22dd385ac2660817bf28 was the only mention.  The other hits for v4 are because gormstore depends on pgx@v4.

**Comment by alexedwards** [comment]
@zaeph Thanks!

**Pull request merged**
